import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/custome/Header'

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        <title>wisata-app</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <Header />
        <div
          className='h-full w-full'
        >
          {children}
        </div>
      </body>
    </html>
  );
}
